### ISSUE TITLE
동일인 유사도 평가 지표 만들기

### ISSUE THREAD

**Issue by proportionequation** [SweetBrothers/sweetbrothers#10]
## 설명(Description)

두 이미지가 동일인물이라고 판별할수 있는 threshold를 결정한다.

## 할 일(Tasks)

- 정성평가
- MediaPipe
- [SGM(Seeded Graph Maching)] 찾아보기

## 참조(References)

- https://velog.io/@jpseo99/SGMSeeded-Graph-Maching-Network%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

**Comment by ahfmrptEkd** [comment]
동일 유사도 에 너무 매몰되지 말아요

**Comment by ahfmrptEkd** [comment]
정성적 평가로 결정이 되었습니다.
