### ISSUE TITLE
SSD-1B TEST

### ISSUE THREAD

**Issue by proportionequation** [SweetBrothers/sweetbrothers#17]
## 설명(Description)

SSD-1B  TEST

## 할 일(Tasks)

- XL 의 경량화 및 추론 속도가 빨라진 버전인 모델 사용 테스트

## 참조(References)

- (https://www.google.com/)](https://github.com/segmind/SSD-1B/issues)

**Comment by proportionequation** [comment]
Out-of-Scope Use
The SSD-1B Model is not suitable for creating factual or accurate representations of people, events, or real-world information. It is not intended for tasks requiring high precision and accuracy.

**Comment by proportionequation** [comment]
https://huggingface.co/segmind/SSD-1B

**Comment by ahfmrptEkd** [comment]
진행상황은 어느정도 개발되었나요?

**Comment by proportionequation** [comment]
cli로 이미지 출력 가능한 상황이고,
지금 LoRA 학습 단계에서 멈춰있습니다

**Comment by proportionequation** [comment]
LoRA 학습 1차 성공

**Comment by ahfmrptEkd** [comment]
copy of #16
