### ISSUE TITLE
그라디오 vs 스트리 밋 

### ISSUE THREAD

**Issue by Jung110** [SweetBrothers/sweetbrothers#19]
## 설명(Description)

그라디오와 스트리밋의 장단점 비교

## 참조(References)

- [Streamlit](https://streamlit.io/)
- [Gradio](https://www.gradio.app/)

**Comment by Jung110** [comment]
## 스트리밋

- 사용자 정의: Streamlit은 사전 정의된 위젯을 제공하는 동시에 사용자 정의도 지원하므로 개인화된 테마와 레이아웃으로 앱을 디자인할 수 있습니다.
- 광범위한 언어 지원: Streamlit은 주로 Python 기반이지만 여러 언어를 지원하므로 더 광범위한 개발자가 액세스할 수 있습니다.
- 원활한 통합: Matplotlib, Plotly, Pandas와 같은 널리 사용되는 라이브러리를 원활하게 통합하여 동적인 대화형 시각화를 생성할 수 있습니다.
- 배포: Streamlit 앱은 공유하기 쉽습니다. 클라우드 서비스 및 로컬 서버를 포함한 다양한 플랫폼에 배포할 수 있습니다.

## 그라디오

- 다양한 입력 유형: Gradio는 이미지, 텍스트에서 오디오에 이르기까지 광범위한 입력 유형을 지원합니다. 이러한 다양성은 다양한 데이터 형식을 처리할 때 특히 유용합니다.
- 다중 모델 통합: Gradio의 뛰어난 기능 중 하나는 여러 모델에 대한 인터페이스를 생성하여 앙상블 배포 및 모델 비교를 촉진하는 기능입니다.
- 공유 가능한 URL: Gradio를 사용하면 모델 인터페이스를 URL로 공유하여 이해관계자와 쉽게 협업하고 공유할 수 있습니다.
- 적대적 견고성: Gradio는 적대적 공격에 대한 보호 수준을 제공하여 배포된 모델의 보안을 강화합니다.

**Comment by MARKZZAM** [comment]
webui는 그라디오 사용한 것으로 보임

**Comment by Jung110** [comment]
https://medium.com/@ShahabH/streamlit-vs-gradio-a-comprehensive-comparison-cc2f28b7b832

**Comment by Jung110** [comment]
## 비교 
Gradio, Streamlit, dash는 인터랙티브 웹 앱 제작을 더 쉽게 만드는 데 탁월한 세 가지 프레임워크입니다. Gradio는 머신 러닝 모델 인터페이스를 구축하는 데 가장 적합하며, stable diffusion / koAlpaca 등 인기 있는 모델들의 서비스 인터페이스로 사용되고 있습니다. Streamlit은 데이터 중심 앱 및 시각화에 가장 적합하며, 신규 AI 모델 시스템을 구축하려고 한다면 1순위로 고려해 볼만한 옵션입니다. Dash는 복잡한 분석 대시보드를 만드는데 가장 적합하다는데, 실제로 많이 접해 보지를 못했네요. 학습 곡선의 영향이 있는 것 같습니다.

[출처](https://bigdatapy.tistory.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%9B%B9-%EC%95%B1-%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC-gradio-steamlit-dash-%EB%B9%84%EA%B5%90)

**Comment by Jung110** [comment]
그러므로 저희는 데이터 중심이기보다는 다중 모델에 초점을 둔 서비스의 MVP를 제작하기 때문에 그라디오가 더 적합하다고 생각합니다.
