### ISSUE TITLE
ds 온프레미스 환경 다시 설정 

### ISSUE THREAD

**Issue by Jung110** [SweetBrothers/sweetbrothers#23]
## 설명(Description)

저장 공간을 /home 경로에 마운트 함에 따라 내부에 있던 유저 파일이 전부 날라감
고로 다시 세팅할 필요가 있음 

**_DS분들이 보고 필요한 것 없으면 이슈를 닫기 바람_**

## 할 일(Tasks)

- [x] 기존에 남아있던 ds  계정 삭제
- [x] 새로운 유저 ds 생성
- [x] 유저에게 권한 부여

**Comment by ahfmrptEkd** [comment]
너무 좋습니다. 생성이랑 환경설정이 다되어서 프로그램은 제가 설치하겠습니다.
