### ISSUE TITLE
Prompt 연구

### ISSUE THREAD

**Issue by ahfmrptEkd** [SweetBrothers/sweetbrothers#30]
## Description
- 실사화 작업을 위한 prompt 연구와 개발 일정을 기입할 예정입니다.
- 이 부분은 "주영" 님이 맡아서 해주실 예정이시고, 연구 과정을 업로드 해주실 예정입니다.

우선 프롬프트에 정답은 없으며 아직까지는 논문에서도 경험적, 귀납적으로 잘되는 방법을 찾으면 된다~ 라 기술합니다. 여러가지 샘플링 메소드, 셋팅을 조절해가면서 괜찮은 프롬프트 추려서 정리해두겠습니다.

**Comment by Zivil97** [comment]
**긍정 프롬프트**
A portrait capturing the essence of a Korean idol, featuring a young woman with clear, radiant skin and a soft, contemplative expression under cool-toned lighting. She wears a white turtleneck, enhancing a pure and serene vibe, with her hair elegantly tied back. The pale blue backdrop complements her cool skin tones. The focus is on her face, centered in the image, with her gaze slightly upward, reflecting a moment of quiet reflection, reminiscent of the tranquility of a winter's day.

**부정 프롬프트**
deformed, disfigured, worst quality, poorly drawn hands, poorly drawn faces, low quality, Blurry, Duplicated features, bad art, Mutation, Ugly, blurry, anime, cartoon

**아웃풋 이미지**
![00025-4287205166](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/fca87976-d0d9-4e19-8444-25a4d6ac9478)

![00026-4287205167](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/0a5a13ce-3ab4-46b2-b209-e293465ec833)

**Sampling method**
DPM++ 2M Karras

**Sampling steps**
60

**CFG Scale**
9

**Comment by Zivil97** [comment]
![image (3) 복사본 3](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/3e48ba32-e04b-45d6-a2e9-8f5ca08b0684)

**Comment by Zivil97** [comment]
긍정 프롬프트
(ultra realistic:1.4), (highly detailed:1.4), (Korean idol:1.2), (sharp focus:1.4), (professional color grading:1.4), (studio portrait:1.3), (HDR:1.2), (4K resolution:1.3), (masterpiece:1.4), (best quality:1.4), (ultra high resolution:1.4), (photo-realistic:1.4), (RAW photo effect:1.2), (ultra-detailed skin texture:1.3), (soft yet defined facial features:1.3), (elegant attire:1.2), (subtle jewelry:1.2), natural beauty, pristine lighting conditions, timeless elegance, (lifelike:1.4)

부정 프롬프트
deformed, disfigured, worst quality, poorly drawn hands, poorly drawn faces, low quality, Blurry, Duplicated features, bad art, Mutation, (worst quality, poor details:1.4)

input image
![image (3) 복사본 3](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/597955d8-b1d3-4476-9894-8e79811cc4e1)

output image
![00010-1139208365](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/c7b54f72-af9c-4142-ab34-cb42e0285398)
![00027-2605619966](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/783ecd36-eca2-4100-a216-2f4f7d504300)

**sampling method** 
DPM++ 2M Karras

**Comment by Zivil97** [comment]
텍스트 투 이미지 

**긍정 프롬프트**
A portrait capturing the essence of a Korean idol, featuring a young woman with clear, radiant skin and a soft, contemplative expression under cool-toned lighting. She wears a white turtleneck, enhancing a pure and serene vibe, with her hair elegantly tied back. The pale blue backdrop complements her cool skin tones. The focus is on her face, centered in the image, with her gaze slightly upward, reflecting a moment of quiet reflection, reminiscent of the tranquility of a winter's day.

**부정 프롬프트**
deformed, disfigured, worst quality, poorly drawn hands, poorly drawn faces, low quality, Blurry, Duplicated features, bad art, Mutation, (worst quality, poor details:1.4)
![00003-2329647941](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/4fec7f65-b811-4731-bcbf-f97653432d0a)
![00005-2329647943](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/03fd0184-a7fe-4e35-bbfb-216350b0e662)
![00006-2329647944-1](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/60d7f853-29f6-42ff-84b7-253563a2fccc)
![00011-2329647949](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/a5ab86db-1c8b-483f-9802-5572762fbd51)

![Uploading 스크린샷 2023-11-27 오후 3.29.38.png…]()

**Comment by Zivil97** [comment]
**긍정프롬프트**
(simple background:1.4), (id photo:1.2), (upper body:1.2), detailed skin, distinct image, detail face, 8k, uhd, intricate quality, intricate details, Realistic, photorealistic, photograph, ultra high res, high resolution, masterpiece, best quality, 1girl, solo, long hair, black eyes, (full bangs, straight bangs), (wavy hair:1.3), sharp nose, looking at viewer, cinemamic lighting, cute, kpop idol, (school uniform:1.4)

**부정프롬프트**
(worst quality, normal quality, low quality:1.5)

![00006-101644792](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/55c7d476-d360-4380-aefa-aa26a9aa22c2)
![00007-101644793](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/46b6b2a5-3b6c-4186-8526-9601887ced9a)
![00004-101644790](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/7535355e-75a6-43ea-a7f5-450c9e40809b)

**Comment by Zivil97** [comment]
**포즈 학습용 이미지**
![20190611141549971_DE9M265F](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/e81a7bb0-b0a4-4862-9f03-d916723d4857)
![BM3I2956](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/272bb7b7-98f1-4556-82e4-1afceea7d52c)
![IMG_3231](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/9eba4135-bfc7-451e-9628-06e69a1ba22d)
![IMG_3319](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/def02c71-b4ad-4c58-8695-6438eab39bf9)
![images](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/7c6302c0-a471-4e19-a079-ee4f3ce1615f)
![IMG_7703](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/dd1f3da5-1c41-4fb6-b0ba-6ba8dad99c02)
![IMG_2157](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/d0715642-f5d9-4138-80b2-fec961c066de)
![IMG_2213](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/1c171df8-eea4-47c4-9586-676cf40ab2e5)
![IMG_3810](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/320f9773-ef81-44c2-8bae-fee3bdfb85a4)
![img1](https://github.com/SweetBrothers/sweetbrothers/assets/132062730/d51a294f-8bc2-44de-bb8c-eb65d1dac186)

**Comment by ahfmrptEkd** [comment]
![image](https://github.com/SweetBrothers/sweetbrothers/assets/108009075/3841cbbb-5b02-4cb2-8fd7-b7fbe45f321c)
이미지 추천 해상도입니다.

**Comment by ahfmrptEkd** [comment]
## base prompt

- 아래의 단에서 성별만 변수입니다. 
- 아래의 코드의 발전이 목표입니다.

```
(((1male:2))),Ultra-realistic 8k CG,masterpiece,best quality,(photorealistic:1.4),absurdres,HDR,RAW photo,Professional,(film grain:1.1),Bokeh,((Depth of field)),raytracing,sunlight, professional color graded, ultra highre,uhd, telephoto lens, Highly detailed
, professional photograph of a stunning detailed, (perfect korean:1.4),upper body, dramatic, blurry background, blurry foreground, interaction, sharp focus, smiling, (casual wear:1.4), extremely intricate, realistic, (clear brown background:1.4), portrait, front, <lora:add_detail:0.5>,  <lora:Better Portrait Lighting:0.5> <lora:epi_noiseoffset2:1> <lora:epiCRealismHelper:1> <lora:epiCRealLife:0.5> <lora:FilmVelvia3:0.5>

((nsfw)), nipples,paintings, sketches, (low quality:2),(normal quality:2),(worst quality:2),lowres,((monochrome)),((grayscale)),acnes,skin spots,age spot,skin blemishes,bad feet,((wrong feet)),(wrong shoes),bad hands,distorted,blurry,missing fingers,multiple feet,bad knees,extra fingers, body hair, bad eye, bad focus, earrings, bad-picture-chill-75v,easynegative, ng_deepnegative_v1_75t
```

**Comment by ahfmrptEkd** [comment]
추가 적인 문제가 있음.

- Positive prompt 와 Negative prompt에서의 토큰이 둘다 75 이상임. 
- Prompt가 둘다 정확하게 유도가 되지않는 현상이 있음.

**Comment by ahfmrptEkd** [comment]
## upgraded base prompt v1

```
"base "
portrait photograpy of front shot, (1boy:1.4),(male:1.2), upper body,(studio clear brown background),casual wear,(ultra realistic),(highly detailed),intricate,(sharp focus),(professional color graded),(professional photograph),hdr,uhd,4k,8k,64k,(masterpiece),(best quality),(ultra highres),(photo realistic),(RAW photo), ultra detailed

nsfw, paintings, sketches, (low quality:2),(normal quality:2),(worst quality:2),lowres,((monochrome)),((grayscale)),acnes,skin spots,age spot,skin blemishes,bad feet,((wrong feet)),(wrong shoes),bad hands,distorted,blurry,missing fingers,multiple feet,bad knees,extra fingers,, body hair, bad eye, bad focus, Accessories, bad-picture-chill-75v, easynegative, ng_deepnegative_v1_75t
```

**Comment by Zivil97** [comment]
**75토큰 이내의 i2i에서 이미지 보정용 프롬프트**

Realistic and detailed, with a focus on expressive eyes and natural smile. The background should be subtle and not distracting. Emphasize natural lighting and lifelike skin tones. Aim for a high-resolution image that captures the essence of a professional studio photograph. Use (realistic:1.5) to enhance the realism and (detailed:1.2)

**Comment by ahfmrptEkd** [comment]
## base prompt v1.01

```
portrait photograpy of front shot, 1girl,female, upper body,(studio clear brown background),casual wear,(ultra realistic),(highly detailed),intricate,(sharp focus),(professional color graded),(professional photograph),hdr,uhd,4k,8k,64k,(masterpiece),(best quality),(ultra highres),(photo realistic),(RAW photo), ultra detailed

nsfw, paintings, sketches, (low quality:2),(normal quality:2),(worst quality:2),lowres,acnes,skin spots,age spot,skin blemishes,bad feet,((wrong feet)),(wrong shoes),bad hands,distorted,blurry,missing fingers,multiple feet,bad knees,extra fingers,, body hair, bad eye, bad focus, bad-picture-chill-75v, easynegative, ng_deepnegative_v1_75t
```

**Comment by ahfmrptEkd** [comment]
## final prompt 완성 (12/08)
