### ISSUE TITLE
시스템 아키택쳐 작성

### ISSUE THREAD

**Issue by MARKZZAM** [SweetBrothers/sweetbrothers#9]
## 설명(Description)

시스템 아키택처 작성

## 할 일(Tasks)

- [x] #13

## 참조(References)

- https://d2908q01vomqb2.cloudfront.net/2a459380709e2fe4ac2dae5733c73225ff6cfee1/2023/10/17/codemafia_arch-1.png

**Comment by ahfmrptEkd** [comment]
자원 지원에 따라 최종 아키텍쳐만 구현 하면 될 것 같습니다.

**Comment by MARKZZAM** [comment]
최종안이 아닌 발표용입니다. 
러프하게 작성한 것으로 추후에 수정할 계획입니다.
